/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FenetreJframe;

import classDAO.ConnexionDAO;
import classDAO.offrecastingDAO;
import classname.Administrateur;
import classname.Connexion;
import classname.OffreCasting;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import megacasting.Bdd;

/**
 *
 * @author AJOURD
 */
public class MegaCasting extends javax.swing.JFrame {

    
    /**
     * Creates new form MegaCasting
     */
    public MegaCasting() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgConnexion = new javax.swing.JPanel();
        titleConnexion = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        mdp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mdpInput = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleConnexion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleConnexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleConnexion.setText("CONNEXION A L'ADMINISTRATION");
        titleConnexion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("Adresse Mail");
        email.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        emailInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        mdp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mdp.setText("Mot de Passe");
        mdp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("CONNEXION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BgConnexionLayout = new javax.swing.GroupLayout(BgConnexion);
        BgConnexion.setLayout(BgConnexionLayout);
        BgConnexionLayout.setHorizontalGroup(
            BgConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(emailInput, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(mdp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mdpInput)
        );
        BgConnexionLayout.setVerticalGroup(
            BgConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgConnexionLayout.createSequentialGroup()
                .addComponent(titleConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mdp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mdpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Connection cn;
        try{
            cn = Bdd.open();
            String inputEmail = emailInput.getText();
            String inputMdp = mdpInput.getText();
            Administrateur admin = new Administrateur(inputEmail, inputMdp);
            ConnexionDAO.connexion(cn, admin);
            Bdd.close((com.mysql.jdbc.Connection) cn);
        } catch (ClassNotFoundException ex){
            Logger.getLogger(MegaCasting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex){
            Logger.getLogger(MegaCasting.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        /*Connection cn;
        try {
            cn = Bdd.open();
            OffreCasting temp = new OffreCasting("test", "fds", "01/01/01 01:01:01", "01/01/01 01:01:01", 5, 2, "Rouen", "pouet", "pouetUnDeux", 4564, 1);
            offrecastingDAO.create(cn, temp);
            Bdd.close((com.mysql.jdbc.Connection) cn);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MegaCasting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MegaCasting.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MegaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MegaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MegaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MegaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MegaCasting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgConnexion;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mdp;
    private javax.swing.JPasswordField mdpInput;
    private javax.swing.JLabel titleConnexion;
    // End of variables declaration//GEN-END:variables
}
